### ISSUE TITLE
[Question] Git server

### ISSUE THREAD

**Issue by Weasy666** [chrisdickinson/git-rs#7]
If seen that you also want to implement the network protocol. What i would like to know is, if it would be possible to then run this crate on a server as a [git server](https://www.git-scm.com/book/en/v2/Git-on-the-Server-The-Protocols), serving repositories, accepting code pushes and so on.

And...are you still planning to make this thing happen? Would really like to have a fast, safe and easily useable git library in Rust 😄
I mean...git2-rs is great, but AFAIK it's missing the git server part because of the libgit2 bindings.

**Comment by chrisdickinson** [comment]
I had been waiting on the futures story to settle down before starting on the server parts of this. Luckily it looks like tokio has recently merged the mainline futures changes, so I'd like to take a look at this in the near future!
