### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by aviallon** [chrisdickinson/git-rs#9]
Hello, I just want to know, since your project is an amazing idea :
have you any plans on continuing it or is it on the shelf for an indefinite amount of time ?
Thanks !

**Comment by wmanley** [comment]
You might be interested in [gitoxide](https://github.com/Byron/gitoxide) if you want to contribute to an implementation of git in rust that's still active.

**Comment by Nukesor** [comment]
@chrisdickinson Would you mind adding a notice to the README and crates.io that this project is no longer actively developed :)

It would also be awesome if you could add a short note for gitoxide, as this seems to be the best pick at the moment.

Thanks in advance!

**Comment by chrisdickinson** [comment]
Hi! I added a link to gitoxide in the README for folks looking for a Git library to use in anger :smile:

This project _is_ maintained, just... a little sporadically, when-and-as I have time! Thanks for your interest.
